### ISSUE TITLE
Training Failed

### ISSUE THREAD

**Issue by beddows** [arcee-ai/arcee-python#22]
When trying to train a new model (with a new context), I get the message: 'status': 'Training failed (RuntimeError)'

**Comment by Jacobsolawetz** [comment]
Hello @beddows! Great to hear from you. We have discovered a non-deterministic bug in our upload flow that is causing this. We will keep you posted on the fix

**Comment by Jacobsolawetz** [comment]
@beddows confirming here that this is an issue with our upload APIs getting overwhelmed. Will keep you posted

**Comment by beddows** [comment]
Ok, thanks for letting me know @Jacobsolawetz

**Comment by Jacobsolawetz** [comment]
@beddows we have healed these APIs - wondering, about how large is the context you are uploading?

You should have a green light to continue below 500K or so. We were getting some large uploads last week which overwhelmed upload infra

**Comment by beddows** [comment]
Thanks @Jacobsolawetz , will check it out! The context file I uploaded was no more than 100k with under 100 rows.

**Comment by Jacobsolawetz** [comment]
@beddows let me know! An for 100K wait perhaps 10-20min after upload for it to drain through before train kickoff - we'll have better fully ACK'd upload status soon
